// 8.JS Web/ReactJS/15.Project Defense/exam-project/src/components/user/login.js
import React, { Component } from 'react'
import requester from '../../Infrastructure/remote'

import observer from '../../Infrastructure/observer';

import { Redirect } from 'react-router-dom';

export default class Login extends Component {

        constructor(props) {
            super(props);
    
            this.state = {
                username: null,
                password: null,
                message: ''
            }
        }
    
        handleChange = (ev) => {
            
            let fieldName = ev.target.name;
            let fieldValue = ev.target.value;
    
            this.setState({
                [fieldName]: fieldValue
            })
        }
    
        handleSubmit = (ev) => {
            ev.preventDefault();



    
            requester.post('user', 'login', 'basic', this.state)
                .then(res => {
                    console.log(res)
                    sessionStorage.setItem('authtoken', res._kmd.authtoken);
                    
                    localStorage.setItem('username', res.username);
                    
                    if(res._kmd.roles){
                        localStorage.setItem('admin', 'true');
                    }else{
                        localStorage.setItem('admin', 'false');
                    }
                
                    observer.trigger(observer.events.loginUser, res.username);    
                
                    observer.trigger(observer.events.notification, {success: true, message: "LoggedIn Successfully!", type: 'success'})
                    


                    this.setState({
                        message: "LoggedIn Successfully!"
                    });

                    this.props.history.push('/home')
                })
                .catch(res => {
                    
                    observer.trigger(observer.events.notification, {error: true, message: "Invalid User Credentials!", type: 'error'})
                    
                    this.setState({
                        message: "Invalid User Credentials!"
                    });

                });        
            }
    


    render() {

        if(localStorage.getItem('username'))
        {
            return <Redirect to='/' />
        }

        return (

            <div>
            <main className="mt-3">
                <h1 className="text-center">Login</h1>
                <hr className="bg-secondary half-width" />
                <form className="mx-auto half-width" onSubmit={this.handleSubmit}>
                    <div className="form-group">
                        <label htmlFor="username">Username</label>
                        <input type="text" onChange={this.handleChange} className="form-control" id="username" placeholder="Username..." name="username" />
                    </div>
                    <div className="form-group">
                        <label htmlFor="password">Password</label>
                        <input type="password" onChange={this.handleChange} className="form-control" id="password" placeholder="Password..." name="password" />
                    </div>
                    <div className="button-holder d-flex justify-content-center">
                        <input type="submit" className="btn chushka-bg-color" value="Login" />
                    </div>
                </form>
            </main>
            <br/>
            <h1 className="text-center danger">{this.state.message}</h1>
            </div>
            )
    }
}

// 8.JS Web/Angular 2/06.Forms Exercise/lesson-and-forms-exercise/src/authentication/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { RegisterModel } from '../models/register.model';
import { LoginModel } from '../models/login.model';
import { AuthService } from '../auth.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  public model : LoginModel;
  public error : Boolean;
  public errorMessage : String;

  constructor(private authService: AuthService, private router : Router) { 
    this.model = new LoginModel("", "");
    this.error = false;
    this.errorMessage = "";
  }

  ngOnInit() {
  }

  login(){
    
    this.authService
    .login(this.model)
    .toPromise()
    .then((res : any) => {
      console.log("LOGGED IN")
      console.log(res)
  
      //save name to localstorage
      this.authService.authtoken = res._kmd.authtoken;
      this.authService.username = res.username;
      localStorage.setItem("authtoken", res._kmd.authtoken);
      localStorage.setItem('username', res.username);
      
      console.log(this.authService.authtoken);
      console.log(this.authService.username);
  
      //redirect to home page
      this.router.navigate(['/']);

    }).catch(err => {
      console.log("ERROR")
      console.log(err);

      if(err){
        this.error = true;
        this.errorMessage = err.error.description;
      }
    }); 
  }
}


<br/>
<br/>
<div class="container">
  <h1>Login Form</h1>
  <br/>
  <form #loginForm="ngForm" (ngSubmit)="login()">
    <div class="form-group">
      <label for="username">Username</label>
      <input type="text" class="form-control" id="username" 
      required
      name="username"
      [(ngModel)]="model.username" 
      #username="ngModel">
    </div>
    <div *ngIf="username.invalid && !username.pristine" class="alert alert-danger">Username is required!</div>
    
    <div class="form-group">
      <label for="password">Password</label>
      <input type="password" class="form-control" id="password" 
      required
      name="password"
      [(ngModel)]="model.password" 
      #password="ngModel">
    </div>
    <div *ngIf="password.invalid && !password.pristine" class="alert alert-danger">Password is required!</div>
    
    <div *ngIf="error" class="alert alert-danger">{{this.errorMessage}}</div>
    <button [disabled]="loginForm.invalid" type="submit" class="btn btn-success">Login</button>
  </form>
</div>
