// 8.JS Web/ReactJS/15.Project Defense/exam-project/src/components/user/login.js
import React, { Component } from 'react'
import requester from '../../Infrastructure/remote'

import observer from '../../Infrastructure/observer';

import { Redirect } from 'react-router-dom';

export default class Login extends Component {

    constructor(props) {
        super(props);

        this.state = {
            username: null,
            password: null,
            message: ''
        }
    }

    handleChange = (ev) => {

        let fieldName = ev.target.name;
        let fieldValue = ev.target.value;

        this.setState({
            [fieldName]: fieldValue
        })
    }

    handleSubmit = (ev) => {
        ev.preventDefault();




        requester.post('user', 'login', 'basic', this.state)
            .then(res => {
                sessionStorage.setItem('authtoken', res._kmd.authtoken);

                localStorage.setItem('username', res.username);

                if (res._kmd.roles) {
                    localStorage.setItem('admin', 'true');
                } else {
                    localStorage.setItem('admin', 'false');
                }

                observer.trigger(observer.events.loginUser, res.username);

                observer.trigger(observer.events.notification, { success: true, message: "LoggedIn Successfully!", type: 'success' })



                this.setState({
                    message: "LoggedIn Successfully!"
                });

                this.props.history.push('/home')
            })
            .catch(res => {

                observer.trigger(observer.events.notification, { error: true, message: "Invalid User Credentials!", type: 'error' })

                this.setState({
                    message: "Invalid User Credentials!"
                });

            });
    }



    render() {

        if (localStorage.getItem('username')) {
            return <Redirect to='/' />
        }

        return (

            <div>
                <br />
                <br />

                <main className="mt-3 forms">
                    <h1 className="text-center">Login</h1>
                    <hr className="bg-secondary half-width" />
                    <form className="mx-auto half-width" onSubmit={this.handleSubmit}>
                        <div className="form-group">
                            <label htmlFor="username">Username</label>
                            <input type="text" onChange={this.handleChange} className="form-control" id="username" placeholder="Username..." name="username" />
                        </div>
                        <br />
                        <div className="form-group">
                            <label htmlFor="password">Password</label>
                            <input type="password" onChange={this.handleChange} className="form-control" id="password" placeholder="Password..." name="password" />
                        </div>
                        <div className="button-holder d-flex justify-content-center">
                            <input type="submit" className="btn btn-success" value="Login" />
                        </div>
                    </form>
                </main>
                <br />
                <h1 className="text-center danger">{this.state.message}</h1>
                <br />
                <br />

            </div>

        )
    }
}

// 8.JS Web/Angular 2/14.Exam Project/comix-shop/src/app/components/auth/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { NgForm } from '@angular/forms';
import { AuthService } from '../auth.service';
import { Router } from '@angular/router';
import { ToastrService } from 'ngx-toastr';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  constructor(
    private authService: AuthService,
    private router: Router,
    private toastr: ToastrService) { }

  ngOnInit() {
  }

  login(f: NgForm) {
    const username = f.value.username;
    const password = f.value.password;

    this.authService.login({ username, password })
      .toPromise().then((data: any) => {

        this.authService.authtoken = data._kmd.authtoken;
        this.authService.username = data.username;
        this.authService.email = data.email;

        if (data._kmd.hasOwnProperty('roles')) {
          this.authService.role = "Admin";
        }
        else {
          this.authService.role = "User";
        }

        localStorage.setItem('authtoken', this.authService.authtoken);
        localStorage.setItem('username', this.authService.username);
        localStorage.setItem('email', this.authService.email);
        localStorage.setItem('role', this.authService.role);

        this.toastr.success('Login successfull!', 'Success!');
        this.router.navigate(['/home']);
      })
      .catch(err => this.toastr.error(err.error.error, 'Error!'))

  }

}

<main class="col-4 ml-auto mr-auto text-center">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="text-center">
                    <h1 class="display-3">Login</h1>
                </div>
                <br/>
                <form #f="ngForm" (ngSubmit)="login(f)">

                    <div class="form-group row">
                        <label class="sr-only">Username</label>
                        <input class="form-control" required name="username" type="text" id="username" placeholder="Username" ngModel #username/>
                    </div>

                    <div class="form-group row">
                        <label class="sr-only">Password</label>
                        <input class="form-control" required type="password" name="password" placeholder="Password" id="password" ngModel #password/>
                    </div>

                    <input [disabled]="f.invalid" type="submit" class="btn btn-outline-warning btn-lg btn-block" value="Login" />
                </form>
                <br/>
            </div>
        </div>
    </div>
</main>
