// 8.JS Web/ReactJS/15.Project Defense/exam-project/src/components/common/header.js
import React, { Component } from 'react'
export default class header extends Component {


    componentDidMount() {
        // Close the dropdown menu if the user clicks outside of it
        window.onclick = function (event) {
            if (!event.target.matches('.dropbtn')) {

                var dropdowns = document.getElementsByClassName("dropdown-content");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (openDropdown.classList.contains('show')) {
                        openDropdown.classList.remove('show');
                    }
                }
            }
        }
    }


    myFunction() {
        document.getElementById("myDropdown").classList.toggle("show");
    }


    render() {


        if (localStorage.getItem('admin') === 'true') {

            return (
                <div className="headerDiv">
                    <header>

                        <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
                            <a className="navbar-brand" href="/house-shop/">HouseShop</a>
                            <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                                <span className="navbar-toggler-icon"></span>
                            </button>

                            <div className="collapse navbar-collapse" id="navbarColor02">
                                <ul className="navbar-nav mr-auto">

                                    <li className="nav-item">
                                        <a className="nav-link nav-link-white" href="/house-shop">Home</a>
                                    </li>

                                    <li className="nav-item">
                                        <a className="nav-link nav-link-white" href="/house-shop/about">About</a>
                                    </li>

                                    <li className="nav-item">
                                        <a className="nav-link nav-link-white" href="/house-shop/user/profile/:id">Profile</a>
                                    </li>

                                    <li className="nav-item">
                                        <a className="nav-link nav-link-white" href="/house-shop/order/my">My Orders</a>
                                    </li>

                                </ul>

                                <div className="dropdown">
                                    <button onClick={this.myFunction} className="dropbtn">[ Admin &#8691; ]</button>
                                    <div id="myDropdown" class="dropdown-content">
                                        <a className="nav-link nav-link-white" href="/house-shop/house/create">Create House</a>
                                        <a className="nav-link nav-link-white" href="/house-shop/order/all">All Orders</a>
                                    </div>
                                </div>

                                <ul className="navbar-nav left-side">
                                    <li className="nav-item">
                                        <a className="nav-link nav-link-white" href="/house-shop/user/logout">Logout</a>
                                    </li>
                                </ul>
                            </div>
                        </nav>

                    </header>
                </div>)
        }

        if (localStorage.getItem('username')) {
            return (

                <div className="headerDiv">
                    <header>
                        <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
                            <a className="navbar-brand" href="/house-shop/">HouseShop</a>
                            <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                                <span className="navbar-toggler-icon"></span>
                            </button>

                            <div className="collapse navbar-collapse" id="navbarColor02">
                                <ul className="navbar-nav mr-auto">

                                    <li className="nav-item">
                                        <a className="nav-link nav-link-white" href="/house-shop/">Home</a>
                                    </li>

                                    <li className="nav-item">
                                        <a className="nav-link nav-link-white" href="/house-shop/about">About</a>
                                    </li>

                                    <li className="nav-item">
                                        <a className="nav-link nav-link-white" href="/house-shop/user/profile/:id">Profile</a>
                                    </li>

                                    <li className="nav-item">
                                        <a className="nav-link nav-link-white" href="/house-shop/order/my">My Orders</a>
                                    </li>

                                </ul>

                                <ul className="navbar-nav left-side">
                                    <li className="nav-item">
                                        <a className="nav-link nav-link-white" href="/house-shop/user/logout">Logout</a>
                                    </li>
                                </ul>
                            </div>
                        </nav>
                    </header>
                </div>)
        }


        return (
            <div className="headerDiv">
                <header className="header">
                    <nav className="navbar navbar-expand-lg navbar-dark bg-dark nav">
                        <a className="navbar-brand" href="/house-shop/">HouseShop</a>
                        <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                            <span className="navbar-toggler-icon"></span>
                        </button>

                        <div className="collapse navbar-collapse" id="navbarColor02">
                            <ul className="navbar-nav mr-auto">

                                <li className="nav-item">
                                    <a className="nav-link nav-link-white" href="/house-shop">Home</a>
                                </li>

                                <li className="nav-item">
                                    <a className="nav-link nav-link-white" href="/house-shop/about">About</a>
                                </li>
                            </ul>

                            <ul className="navbar-nav left-side">
                                <li className="nav-item">
                                    <a className="nav-link nav-link-white" href="/house-shop/user/login">Login</a>
                                </li>
                                <li className="nav-item">
                                    <a className="nav-link nav-link-white" href="/house-shop/user/register">Register</a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </header>
            </div>
        )

    }
}

// 8.JS Web/Angular 2/14.Exam Project/comix-shop/src/app/components/common/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from '../../auth/auth.service';
import { Router } from '@angular/router';
import { ToastrService } from 'ngx-toastr';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {

  isAdmin: boolean;
  isAuthenticated: boolean;

  constructor(
    public authService: AuthService,
    private router: Router,
    private toast: ToastrService) { }

  ngOnInit() {
    this.isAdmin = localStorage.getItem("role") === "Admin" ? true : false;
    this.isAuthenticated = localStorage.getItem("authtoken") ? true : false;


// Close the dropdown menu if the user clicks outside of it
window.onclick = function (event : any) {
  if (!event.target.matches('.dropbtn')) {

    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}


  }

  logout() {

    this.authService.logout()
      .toPromise()
      .then(() => {
        this.authService.authtoken = null;
        this.authService.email = null;
        this.authService.role = null;
        this.authService.username = null;
        localStorage.clear();

        this.router.navigate(['/auth/login']);
        this.toast.success('Logout successfull!', 'Success!');
      }).catch(err => this.toast.error(err.error.error, 'Error!'));
  }


  /* When the user clicks on the button, 
toggle between hiding and showing the dropdown content */
  myFunction() {
    document.getElementById("myDropdown").classList.toggle("show");
  }

  

}

<header>
    <nav class="navbar navbar-expand-md navbar-light bg-warning">
        <div class="container">
            <a class="navbar-brand" routerLink="/">Comics Store</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">

                    <li class="nav-item">
                        <a class="nav-link" routerLink="/home">Home</a>
                    </li>
                    <li *ngIf="authService.isAuthenticated()" class="nav-item">
                        <a class="nav-link" routerLink="/comix/all">All Comics</a>
                    </li>
                </ul>

                
                <div class="dropdown" *ngIf="authService.isAdmin()">
                    <button (click)="this.myFunction()" class="dropbtn">[ Admin &#8691; ]</button>
                    <div id="myDropdown" class="dropdown-content">
                        <a class="nav-link" routerLink="/comix/create">[Create Comics]</a>
                        <a class="nav-link" routerLink="/order/all">[All Orders]</a>
                        <a class="nav-link" routerLink="/user/all">[All Profiles]</a>
                    </div>
                  </div>


                <ul class="navbar-nav">
                    <li *ngIf="authService.isAuthenticated()" class="nav-item">
                        <a class="nav-link" routerLink="/order/my">My Orders</a>
                    </li>
                    <li *ngIf="authService.isAuthenticated()" class="nav-item">
                        <a class="nav-link" routerLink="/user/profile">My Profile</a>
                    </li>
                </ul>

                <ul class="navbar-nav">
                    <li *ngIf="!authService.isAuthenticated()" class="nav-item">
                        <a class="nav-link" routerLink="/auth/login">Login</a>
                    </li>
                    <li *ngIf="!authService.isAuthenticated()" class="nav-item">
                        <a class="nav-link" routerLink="/auth/register">Register</a>
                    </li>
                    <li *ngIf="authService.isAuthenticated()" class="nav-item">
                        <a class="nav-link" routerLink="#" (click)="logout()">Logout</a>
                    </li>
                    <li *ngIf="authService.isAuthenticated()" class="nav-item">
                        <a class="nav-link" routerLink="/user/profile">[ Welcome ( {{ authService.username }} ) ]</a>
                    </li>
                </ul>
            </div>
        </div>    
    </nav>
</header>
<br/>
<br/>
