// 8.JS Web/ReactJS/15.Project Defense/exam-project/src/components/common/header.js
import React, { Component } from 'react'
export default class header extends Component {

    render() {


        if (localStorage.getItem('admin') === 'true') {

            return (
                <header>

                    <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
                        <a className="navbar-brand" href="/">HouseShop</a>
                        <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                            <span className="navbar-toggler-icon"></span>
                        </button>

                        <div className="collapse navbar-collapse" id="navbarColor02">
                            <ul className="navbar-nav mr-auto">

                                <li className="nav-item">
                                    <a className="nav-link nav-link-white" href="/">Home</a>
                                </li>

                                <li className="nav-item">
                                    <a className="nav-link nav-link-white" href="/about">About</a>
                                </li>

                                <li className="nav-item">
                                    <a className="nav-link nav-link-white" href="/user/profile/:id">Profile</a>
                                </li>

                                <li className="nav-item">
                                    <a className="nav-link nav-link-white" href="/order/my">My Orders</a>
                                </li>

                                <li className="nav-item" >
                                    <a className="nav-link nav-link-white" href="/order/all">All Orders</a>
                                </li>

                                <li className="nav-item">
                                    <a className="nav-link nav-link-white" href="/house/create">Create House</a>
                                </li>

                            </ul>

                            <ul className="navbar-nav left-side">
                                <li className="nav-item">
                                    <a className="nav-link nav-link-white" href="/user/logout">Logout</a>
                                </li>
                            </ul>
                        </div>
                    </nav>

                </header>)
        }

        if (localStorage.getItem('username')) {
            return (<header>
                
                
                <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
                        <a className="navbar-brand" href="/">HouseShop</a>
                        <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                            <span className="navbar-toggler-icon"></span>
                        </button>

                        <div className="collapse navbar-collapse" id="navbarColor02">
                            <ul className="navbar-nav mr-auto">

                                <li className="nav-item">
                                    <a className="nav-link nav-link-white" href="/">Home</a>
                                </li>

                                <li className="nav-item">
                                    <a className="nav-link nav-link-white" href="/about">About</a>
                                </li>

                                <li className="nav-item">
                                    <a className="nav-link nav-link-white" href="/user/profile/:id">Profile</a>
                                </li>

                                <li className="nav-item">
                                    <a className="nav-link nav-link-white" href="/order/my">My Orders</a>
                                </li>

                            </ul>

                            <ul className="navbar-nav left-side">
                                <li className="nav-item">
                                    <a className="nav-link nav-link-white" href="/user/logout">Logout</a>
                                </li>
                            </ul>
                        </div>
                    </nav>

            </header>)
        }


        return (

            <header className="header">
                 <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
                        <a className="navbar-brand" href="/">HouseShop</a>
                        <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                            <span className="navbar-toggler-icon"></span>
                        </button>

                        <div className="collapse navbar-collapse" id="navbarColor02">
                            <ul className="navbar-nav mr-auto">

                                <li className="nav-item">
                                    <a className="nav-link nav-link-white" href="/">Home</a>
                                </li>

                                <li className="nav-item">
                                    <a className="nav-link nav-link-white" href="/about">About</a>
                                </li>
                            </ul>

                            <ul className="navbar-nav left-side">
                            <li className="nav-item">
                                    <a className="nav-link nav-link-white" href="/user/login">Login</a>
                                </li>
                                <li className="nav-item">
                                    <a className="nav-link nav-link-white" href="/user/register">Register</a>
                                </li>
                            </ul>
                        </div>
                    </nav>
            </header>
        )

    }
}

// 8.JS Web/Angular 2/13.Workshow Two, with FireBase and Redux/workshop-two/src/app/components/common/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from '../../auth/auth.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})

export class HeaderComponent implements OnInit {

  dropdownLi : string = "nav-item dropdown";
  dropdownMenu : string = "dropdown-menu";

  constructor(private authService : AuthService){}

  ngOnInit() {
  }

  expand() {
    this.dropdownLi.endsWith('show') 
    ? this.dropdownLi = "nav-item dropdown" 
    : this.dropdownLi = "nav-item dropdown show";

    this.dropdownMenu.endsWith('show')
    ? this.dropdownMenu = "dropdown-menu"
    : this.dropdownMenu = "dropdown-menu show";
  }

  logout(){
    this.authService.logout();
  }
}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" routerLink="/recipes/start">Recipes</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
          <li *ngIf="!authService.isAuthenticated()" class="nav-item">
              <a class="nav-link" routerLink="/auth/signin">Sign In</a>
            </li>
            <li *ngIf="!authService.isAuthenticated()" class="nav-item">
              <a class="nav-link" routerLink="/auth/signup">Sign Up</a>
            </li>
      <li *ngIf="authService.isAuthenticated()" class="nav-item">
        <a class="nav-link" (click)="logout()">Logout</a>
      </li>
      <li *ngIf="authService.isAuthenticated()" (click)="expand()" [class]="dropdownLi">
        <a class="nav-link dropdown-toggle" id="dropdown01" data-toggle="dropdown"
         aria-haspopup="true" aria-expanded="false">Recipes</a>
          <div [class]="dropdownMenu" aria-labelledby="dropdown01">
           <a class="dropdown-item" routerLink="/recipes/all" >All Recipes</a>
           <a class="dropdown-item" routerLink="/recipes/create">Create</a>
          </div>
      </li>
    </ul>
  </div>
</nav>
